name: Integration
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.java'
      - '**.kt*'
      - .github/workflows/integration.yml
      - api/types.api
      - qodana.yaml
  push:
    branches: [ main, release/* ]
    paths:
      - '**gradle*'
      - '**.java'
      - '**.kt*'
      - .github/workflows/integration.yml
      - api/types.api
      - qodana.yaml
  workflow_dispatch:
env:
  CACHING: gradle
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 17
jobs:
  # ---------- Stage 1 ----------
  gradle-wrapper-validation:
    name: Gradle wrapper validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  static-code-analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Scan code
        uses: JetBrains/qodana-action@v2023.2.8
        with:
          args: --fail-threshold,0
          pr-mode: false
  # ---------- Stage 2 ----------
  js-test:
    name: Kotlin/JS tests
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test 'internal' subproject
        run: ./gradlew :internal:jsTest
      - name: Test root project
        run: ./gradlew :jsTest
  jvm-checks:
    name: Kotlin/JVM checks
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test 'internal' subproject
        run: ./gradlew :internal:jvmTest
      - name: Test 'java-compatibility' subproject
        run: ./gradlew :java-compatibility:test
      - name: Check root project
        run: ./gradlew :jvmTest :jvmApiCheck
  linux-test:
    name: Kotlin Native tests for Linux
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test 'internal' subproject
        run: ./gradlew :internal:linuxTest
      - name: Test root project
        run: ./gradlew :linuxTest
  macos-test:
    name: Kotlin Native tests for macOS
    needs: gradle-wrapper-validation
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test 'internal' subproject
        run: ./gradlew :internal:macosTest
      - name: Test root project
        run: ./gradlew :macosTest
  windows-test:
    name: Kotlin Native tests for Windows
    needs: gradle-wrapper-validation
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test 'internal' subproject
        run: ./gradlew :internal:windowsTest
      - name: Test root project
        run: ./gradlew :windowsTest
  # ---------- Stage 3 ----------
  dependencies:
    name: Dependency graph
    needs:
      - js-test
      - jvm-checks
      - linux-test
      - macos-test
      - static-code-analysis
      - windows-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Submit dependencies to GitHub
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-configuration: allSourceSetsRuntimeDependenciesMetadata
          fail-on-error: true
